### PR TITLE
VM-37: added link field to events

### PR DESCRIPTION
**Pull request by ShreyansT**
I have validated my changes against the acceptance criteria for the addition of a link so that I could mark this user story as complete and able to merge.  The VSA Application is able to show me a list of all the events with the time, points, location, event name, description, date, and associated link of the event and I able to freely update, create, and delete the links for the events if needed. I have checked after doing each of these three operations, that the application has the new list of events that reflects the outcome of those operations. Additionally, I have performed testing with the link field to make sure the results of the user story (the addition of the link field) are verified. I have also following the coding standard and used a two space indentation along with a meaning variable name.

### CODE REVIEW

**Review by sashbhagav — CHANGES_REQUESTED** [review]
Please replace your gemfile.lock with the gemfile.lock in the master branch. The new updates in the gemfile are not compatible with heroku for some reason.

**Comment by ShreyansT** [comment]
Gemfile.lock has been updated to match master. Thanks for reviewing.

**Comment by sashbhagav** [comment]
here is your Heroku Review app: https://vsatracker-vm-37-link-m2g1zk7e.herokuapp.com/

**Comment by ShreyansT** [comment]
Heroku Review App works as intended! I am able to see the link field along with being able to create, update, and delete it

**Review by sashbhagav — APPROVED** [review]
Changes look good. Thanks for updating the gemfile.lock. The rest of your files adhere to the coding standards and the review app works as intended. I will go ahead and merge.

**Comment by dorteg12** [comment]
Great looking at the heroku app created by Sashreek you have followed your definition of done. Your code is following our coding standard

**Comment by mattyC7370** [comment]
Definition of Done is met. No merge conflicts. Looks good to merge..

**Pull request merged**
