### PR TITLE
Vm 44 password protect merge to DEV

### PR DESCRIPTION
**Pull request by sashbhagav**
Followed the coding standards and added in code to hide the password for when the admin types in the password.

### CODE REVIEW

**Comment by ShreyansT** [comment]
Good job adhering to the coding standards. I see the updated code and it follows our 2 space indentation pattern. Please fix these merge conflicts and once they are done I will go ahead and merge depending on the results of the CI test.

**Comment by sashbhagav** [comment]
I have fixed my merge conflicts.

**Comment by ShreyansT** [comment]
Nice job fixing those merge conflicts. Your tests also pass and your branch is ready to be merged!

**Comment by dorteg12** [comment]
Followed the coding standards nice work on fixing conflicts

**Pull request merged**
