### PR TITLE
Vm 38 39 datatables pts memberview

### PR DESCRIPTION
**Pull request by dorteg12**

### CODE REVIEW

**Comment by dorteg12** [comment]
The coding standard was followed and I combined 3 stories into one branch which was putting points on all tables in the website, adding datatables to all tables and implemnting a imprort for points

**Review by sashbhagav — CHANGES_REQUESTED** [review]
Please fix your merge conflicts. Here is your heroku review app. Review it and make sure it works: https://vsatracker-vm-38-39-dat-di9ceq.herokuapp.com/

**Review by sashbhagav — APPROVED** [review]
So your code looks good. You followed the coding standard pretty well. Once the CI test finishes running I will allow you to merge.

**Comment by mattyC7370** [comment]
All merge conflicts were resolved, code looks good.. Followed coding standards well

**Pull request merged**
