### PR TITLE
Added date field to events

### PR DESCRIPTION
**Pull request by ShreyansT**
I adhered to the coding standards while making the updates. I used two space indentation and used db:migrate when I needed to apply the newly added migration of the date field.

### CODE REVIEW

**Review by sashbhagav — CHANGES_REQUESTED** [review]
1. Your CI tests failed so please fix those 
2. There has been a recent update with the mimemagic gem, so run a bundle update and delete the vendor folder, then push. 
3. Once you make these changes let me know, so I can send you the review app

**Comment by sashbhagav** [comment]
Here is your review app: https://vsatracker-vm-36-date-sxx7aiz9.herokuapp.com/
Make sure it works and comment back. I will merge once this is done

**Comment by ShreyansT** [comment]
Review App Is Working as Intended. I am able to create the date for the event and also update if needed. Also I am able to see in both the views along with delete if needed to as well.

**Review by sashbhagav — APPROVED** [review]
1. Code looks good and the changes seemed to have worked. 
2. Your review app is working so thanks for checking that out. 
3. Thanks for fixing merge conflicts earlier. 
Your code is good to be merged into dev.

**Comment by dorteg12** [comment]
Great looking at the heroku app created by Sashreek you have followed your definition of done. Your code is following our coding standard

**Pull request merged**
